spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itheima
    username: root
    password: 123456
  main:
    banner-mode: off #关闭logo

# 配置日志， 输出到控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false #关闭logo
    db-config:
      id-type: assign_id
      table-prefix: tb_  #类名前缀拼接
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

